name: CI

on: push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    strategy:
      matrix:
        node: [lts, 14]
    steps:
      - uses: actions/checkout@master
      
      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      
      - name: Install packages
        run: yarn --frozen-lockfile
      
      - name: Lint
        run: |-
          yarn format-check;
          yarn lint;
      
      - name: Test
        run: yarn test-unit
        
      - name: Build # Tests to see if a build can succeed
        run: yarn build
